# Generated by Django 2.2.8 on 2020-08-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_auto_20200818_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='report',
            new_name='newreport',
        ),
    ]
