# Generated by Django 2.2.8 on 2020-08-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_auto_20200818_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
